language: python
# python:
  # - "2.7"
  # - "3.8"
jobs:
  include:
    - name: "Windows Python27"
      os: windows
      language: sh
      python: "2.7"
      cache: pip
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
      install:
        - pip install -U -r requirements-dev.txt
        - pip install -vvv --user -e .
      script:
        - python tests/testrunner.py && pylint -E _caster.py && pylint -E castervoice

    - name: "Windows Python38"
      os: windows
      language: sh
      python: "3.8"
      cache: pip
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip wheel
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install -U -r requirements-dev.txt
        - pip install -vvv --user -e .
      script:
        - python tests/testrunner.py && pylint -E _caster.py && pylint -E castervoice

    - name: "macOS python38"
      os: macos
      language: sh
      python: "3.8"
      cache: pip
      before_install:
        - python -m pip install --upgrade pip wheel
      install:
        - pip install -U -r requirements-mac-linux.txt
        - pip install -vvv --user -e .
      script:
        - python tests/testrunner.py && pylint -E _caster.py && pylint -E castervoice
