extra_css:
- https://assets.readthedocs.org/static/css/badge_only.css
- https://assets.readthedocs.org/static/css/readthedocs-doc-embed.css
extra_javascript:
- readthedocs-data.js
- https://assets.readthedocs.org/static/core/js/readthedocs-doc-embed.js
- https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js
google_analytics: null
site_name: Caster
site_author: dictation-toolbox
site_url: https://castertest.readthedocs.io
docs_dir: castervoice/doc
site_dir: castervoice/doc_site
repo_url: https://github.com/dictation-toolbox/caster

pages:
    - 'Home': '../../ReadMe.md'
