name: Caster Lint/Unit Tests

on: [push]

jobs:
  python-windows-2-7:
        name: python 2 windows
        runs-on: windows-latest
        strategy:
          matrix:
            python-version: [2.7.x]
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              choco install vcpython27
              python -m pip install --upgrade pip
              pip install --upgrade setuptools
              pip install -U -r requirements-dev.txt
          - name: Lint with pylint
            run: |
              pylint -E _caster.py
              pylint -E castervoice
          - name: Unit Tests Via Testrunner
            run: |
              python tests/testrunner.py

  python-windows-3-8-x:
        name: python 3 windows
        runs-on: windows-latest
        strategy:
          matrix:
            python-version: [3.8.x]
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install --upgrade setuptools
              pip install -U -r requirements-dev.txt
          - name: Lint with pylint
            run: |
              pylint -E _caster.py
              pylint -E castervoice
          - name: Unit Tests Via Testrunner
            run: |
              python tests/testrunner.py

  python-linux-3-8-x:
        name: python 3 linux
        runs-on: ubuntu-20.04
        strategy:
          matrix:
            python-version: [3.8.x]
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              sudo apt-get install libgtk-3-dev
              sudo apt-get install python3-tk
              python -m pip install --upgrade pip
              pip install --upgrade setuptools
              python -m pip install -U https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl
              pip install -U -r requirements-mac-linux.txt
          - name: Lint with pylint
            run: |
              pylint -E _caster.py
              pylint -E castervoice
          - name: Unit Tests Via Testrunner
            run: |
              python tests/testrunner.py

  python-macos-3-8-x:
        name: python 3 MacOs
        runs-on: macos-latest
        strategy:
          matrix:
            python-version: [3.8.x]
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install --upgrade setuptools
              pip install -U -r requirements-mac-linux.txt
          - name: Lint with pylint
            run: |
              pylint -E _caster.py
              pylint -E castervoice
          - name: Unit Tests Via Testrunner
            run: |
              python tests/testrunner.py